"""Reward functions for GRPO training."""

import re


# ============================================================
# REGEX PATTERNS
# ============================================================

# Extract reasoning from model output
match_model_reasoning = re.compile(
    r"<reasoning>\s*(.*?)\s*</reasoning>",
    flags=re.MULTILINE | re.DOTALL,
)

# Extract final answer from model output
match_model_number = re.compile(
    r"<answer>\s*(-?\d+(?:\.\d+)?)\s*</answer>",
    flags=re.MULTILINE | re.DOTALL,
)

# Check complete required format
xml_pattern = re.compile(
    r"^\s*"
    r"<reasoning>\s*.*?\s*</reasoning>\s*"
    r"<answer>\s*-?\d+(?:\.\d+)?\s*</answer>"
    r"\s*$",
    flags=re.DOTALL,
)


# ============================================================
# EXTRACTION FUNCTIONS
# ============================================================

def get_completion_text(completion):
    """
    Convert TRL completion into a plain string.

    Handles:
    1. String:
       "<reasoning>...</reasoning><answer>8</answer>"

    2. Chat format:
       [{"role": "assistant", "content": "..."}]
    """

    if isinstance(completion, str):
        return completion

    if isinstance(completion, list):
        if len(completion) > 0:

            # Chat message format
            if isinstance(completion[0], dict):
                return completion[0].get("content", "")

            # Fallback
            return str(completion[0])

    return str(completion)


def extract_model_reasoning(completion):
    """Extract reasoning generated by the model."""

    text = get_completion_text(completion)

    match = match_model_reasoning.search(text)

    if match:
        return match.group(1).strip()

    return None


def extract_model_answer(completion):
    """Extract model answer."""

    text = get_completion_text(completion)

    # --------------------------------------------------
    # 1. Preferred format:
    # <answer>48</answer>
    # --------------------------------------------------
    match = re.search(
        r"<answer>\s*(-?\d+(?:\.\d+)?)\s*</answer>",
        text,
        flags=re.DOTALL,
    )

    if match:
        return match.group(1).strip()

    # --------------------------------------------------
    # 2. Fallback:
    # Look for final number in model output
    # --------------------------------------------------
    numbers = re.findall(
        r"(?<!\w)-?\d+(?:\.\d+)?",
        text,
    )

    if numbers:
        return numbers[-1]

    return None


def extract_gsm8k_reasoning(text):
    """
    Extract reasoning from GSM8K answer.

    Example:

    'Janet has 5 apples.
     She buys 3 more.
     Therefore, she has 8 apples.
     #### 8'

    Returns:

    'Janet has 5 apples.
     She buys 3 more.
     Therefore, she has 8 apples.'
    """

    if text is None:
        return None

    text = str(text)

    if "####" in text:
        return text.split("####", 1)[0].strip()

    return text.strip()


def extract_gsm8k_answer(text):
    """
    Extract final answer from GSM8K answer.

    This function supports both:

    #### 8

    and

    8
    """

    if text is None:
        return None

    text = str(text).strip()

    # New dataset format:
    # final_answer = "8"
    if re.fullmatch(r"-?\d+(?:\.\d+)?", text):
        return text

    # Original GSM8K format:
    # answer = "... reasoning ... #### 8"
    match = re.search(
        r"####\s*(-?\d+(?:\.\d+)?)",
        text,
    )

    if match:
        return match.group(1).strip()

    return None

# ============================================================
# CORRECT ANSWER REWARD
# ============================================================

def correct_answer_check(
    completions,
    final_answer,
    reasoning=None,
    **kwargs,
):
    """
    Reward correct final numerical answer.

    Reward:
        Exact answer       -> +2.0
        Within 10%         -> +1.0
        Within 20%         -> +0.5
        Incorrect          ->  0.0
        Invalid/missing    -> -0.5
    """

    rewards = []

    for i, (completion, ground_truth) in enumerate(
        zip(completions, final_answer)
    ):

        # Extract model outputs
        model_answer = extract_model_answer(completion)
        model_reasoning = extract_model_reasoning(completion)

        # Extract ground truth
        gsm8k_answer = extract_gsm8k_answer(
            ground_truth
        )

        # Get ground truth reasoning
        if reasoning is not None:
            ground_truth_reasoning = reasoning[i]
        else:
            ground_truth_reasoning = None

        # --------------------------------------------
        # Calculate answer reward
        # --------------------------------------------

        if (
            model_answer is not None
            and gsm8k_answer is not None
        ):

            try:

                model_value = float(model_answer)
                ground_truth_value = float(gsm8k_answer)

                # Exact match
                if model_value == ground_truth_value:

                    answer_reward = 2.0

                else:

                    # Avoid division by zero
                    if ground_truth_value == 0:

                        answer_reward = 0.0

                    else:

                        ratio = (
                            model_value
                            / ground_truth_value
                        )

                        # Within 10%
                        if 0.9 <= ratio <= 1.1:
                            answer_reward = 1.0

                        # Within 20%
                        elif 0.8 <= ratio <= 1.2:
                            answer_reward = 0.5

                        else:
                            answer_reward = 0.0

            except ValueError:

                answer_reward = -0.5

        else:

            answer_reward = -0.5

        rewards.append(answer_reward)
    return rewards
# ============================================================
# XML / FORMAT REWARD
# ============================================================

def xml_reward_system(
    completions,
    **kwargs,
):
    """
    Reward correct output format.

    Correct:

    <reasoning>
    ...
    </reasoning>
    <answer>
    8
    </answer>

    Reward:
        Correct format -> +0.5
        Incorrect format -> -0.5
    """

    rewards = []

    for completion in completions:

        completion_text = get_completion_text(
            completion
        )

        if xml_pattern.fullmatch(
            completion_text
        ):

            rewards.append(0.5)
            continue 
        #partial reward system
        reward=0.0
        if completion_text.count("<reasoning>")==1:
            reward+=0.1
        if completion_text.count("</reasoning>")==1:
            reward+=0.1
        #answer tag
        if completion_text.count("<answer>")==1:
            reward+=0.1
        if completion_text.count("</answer>")==1:
            reward+=0.1
        # no format penalty
        rewards.append(reward)

    return rewards